DROP TABLE IF EXISTS edges;
DROP TABLE IF EXISTS nodes;

CREATE TABLE nodes (
  id INT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  x DOUBLE NOT NULL,
  y DOUBLE NOT NULL
);

CREATE TABLE edges (
  from_id INT NOT NULL,
  to_id INT NOT NULL,
  weight DOUBLE NOT NULL,
  CONSTRAINT fk_from FOREIGN KEY (from_id) REFERENCES nodes(id),
  CONSTRAINT fk_to FOREIGN KEY (to_id) REFERENCES nodes(id)
);


